### ISSUE TITLE
文章目录跳转问题

### ISSUE THREAD

**Issue by ghost** [cayzlh/hexo-theme-yummy#2]
博客文章生成的右侧目录，目录项全部英文字符时，正常跳转；当有中文时，跳转无效。

**Comment by cayzlh** [comment]
这个我看下， 太久没碰这个东东了。。。。

**Comment by cayzlh** [comment]
可以啦。

可在 [这里](https://yummy.cayzlh.com/2020/09/29/API签名验证方案/) 看到效果

**Comment by ghost** [comment]
收到，已解决，干的漂亮，兄弟！
