### ISSUE TITLE
归档页面问题

### ISSUE THREAD

**Issue by ghost** [cayzlh/hexo-theme-yummy#3]
问题：归档页面所列出的文章是主页所列出的所有文章。即主页设定分页为10，则归档里只显示10个文章，这是有问题的。
解决方法：修改 `/_partial/archive-content.ejs` 文件里，第五行代码 `page.posts.sort(…….` 修改为 `site.posts.sort(`，也就是将 page 改为 site。问题即解决。
参考地址：https://hexo.io/zh-cn/api/locals#%E8%8E%B7%E5%8F%96%E6%89%80%E6%9C%89%E5%8F%98%E9%87%8F

**Comment by cayzlh** [comment]
好的， 我改了，提交到master分支了，

**Comment by ghost** [comment]
ok
